### ISSUE TITLE
Remove CSS/Javascript code from HTML

### ISSUE THREAD

**Issue by davit1987** [mariamzakiyan/Store#1]
See the screenshot: 
![bug1](https://cloud.githubusercontent.com/assets/6450498/6439619/ca6d3170-c0ed-11e4-9c6c-7e6ddc5b3f56.png)

**Comment by davit1987** [comment]
Vonc es?

**Comment by mariamzakiyan** [comment]
@davit1987  lav ) du?

**Comment by davit1987** [comment]
Lav em. exav arden mots ashxatuma @mariamzakiyan .

**Comment by mariamzakiyan** [comment]
de es tasky anem ;) @davit1987
