### ISSUE TITLE
Remove shop.zip from repo

### ISSUE THREAD

**Issue by davit1987** [mariamzakiyan/Store#2]

**Comment by davit1987** [comment]
@mariamzakiyan vory anum es paki issue-n.

**Comment by mariamzakiyan** [comment]
@davit1987 ok :+1:

**Comment by davit1987** [comment]
kam assign ara indz es kpakem. Hamel amen agnam pull ara push aneluc araj.

**Comment by mariamzakiyan** [comment]
lav @davit1987
