### ISSUE TITLE
Create a new branch for development

### ISSUE THREAD

**Issue by davit1987** [mariamzakiyan/Store#4]
Create a new branch for development "dev" and checkout on that branch.

**Comment by mariamzakiyan** [comment]
7777777

2015-03-02 16:12 GMT+04:00 davit1987 <notifications@github.com>:

> Assigned #4 <https://github.com/mariamzakiyan/Store/issues/4> to
> @mariamzakiyan <https://github.com/mariamzakiyan>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mariamzakiyan/Store/issues/4#event-244306335>.
>



-- 
--
Best Regards,
Mariam Zakiyan
